version: '2'

networks:
  management:

volumes:
  registry-data:

services:
  registry:
    build: registry
    volumes:
      - registry-data:/var/lib/registry
    ports:
      - "5000:5000"
    networks: 
      - management
    environment: 
      - constraint=node.labels.type==management
      - REGISTRY_PROXY_REMOTEURL=https://registry-1.docker.io
