version: '3.0'

networks:
  plf:

volumes:
  plf_node1:
  plf_shared:

services:
  plf1:
    image: exoplatform/exo:5.0_latest
    environment:
      EXO_ADDONS_LIST:
      EXO_ADDONS_REMOVE_LIST:
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: plf
      EXO_DB_USER: plf
      EXO_DB_PASSWORD: plf
      EXO_DB_HOST: db
      EXO_DB_POOL_IDM_INIT_SIZE: 1
      EXO_DB_POOL_IDM_MAX_SIZE: 10
      EXO_DB_POOL_JCR_INIT_SIZE: 2
      EXO_DB_POOL_JCR_MAX_SIZE: 5
      EXO_DB_POOL_JPA_INIT_SIZE: 3
      EXO_DB_POOL_JPA_MAX_SIZE: 20
      EXO_PROXY_VHOST: localhost
      EXO_PROXY_SSL: "false"
      EXO_ES_EMBEDDED: "false"
      EXO_ES_HOST: search
      EXO_PROXY_PORT: 80
#      EXO_CLUSTER: "true"
#      EXO_CLUSTER_HOSTS: "172.16.251.11,172.16.251.12"
#      EXO_JGROUPS_ADDR: "172.16.251.11"
#      EXO_FILE_STORAGE_DIR: /srv/exo/shared/files
#      EXO_JCR_STORAGE_DIR: /srv/exo/shared/jcrvalues

      EXO_JVM_SIZE_MIN: "2g"
      EXO_JVM_SIZE_MAX: "3g"
      EXO_MAIL_SMTP_HOST: "mail"
      EXO_MAIL_SMTP_PORT: "1025"

      EXO_JMX_ENABLED: "true"
      EXO_JMX_RMI_REGISTRY_PORT: 10001
      EXO_JMX_RMI_SERVER_PORT: 10002
      # TODO check is must be changed / parameterized
      EXO_JMX_RMI_SERVER_HOSTNAME: plf1

    volumes:
      - plf_node1:/srv/exo
    networks:
      - db
      - plf
      - search
      - mongo
      - front

  jmxtrans:
    image: exoplatform/jmxtrans:265_1
    container_name: jmxtrans
    environment:
      TARGET_JMX_HOST: plf1
      TARGET_HOSTNAME: plf1
      TARGET_JMX_PORT: 10001
      # TODO parameterize
      TARGET_INFLUXDB_URL: ${INFLUXDB_HOST}
      TARGET_INFLUXDB_DATABASE: exo
      TARGET_INFLUXDB_CREATE_DB: "true"
      JMXTRANS_LOG_LEVEL: info  #warn
      TARGET_NODE_ID: plf1
    networks:
      - plf

