version: '3.0'

networks:
  plf:
    driver: bridge
    # enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: 172.16.251.0/24

services:
  plf02:
    image: exoplatform/exo:5.1_latest
    environment:
      EXO_FILE_STORAGE_DIR: /srv/exo/shared/files
      EXO_JCR_STORAGE_DIR: /srv/exo/shared/jcrvalues
    volumes:
      - /srv/bench/plf02:/opt/exo
      - /srv/bench/data/files:/srv/exo/files
      - /srv/bench/data/jcr/values:/srv/exo/jcr/values
      - /srv/bench/indexes/index02:/srv/exo/jcr/index
    entrypoint: /opt/exo/start_eXo.sh
    expose:
      - 8080
      - 8084
    networks:
      plf:
        ipv4_address: "172.16.251.12"
      search:
      ldap:
      mongo:
      db:
      front:
  plf02_jmxtrans:
    image: exoplatform/jmxtrans:268_1
    environment:
      TARGET_JMX_HOST: plf02
      TARGET_HOSTNAME: qaf05
      TARGET_JMX_PORT: 8004
      TARGET_INFLUXDB_DATABASE: exo
      TARGET_INFLUXDB_URL: http://pro17.exoplatform.org:8086
      TARGET_NODE_ID: plf02
      JMXTRANS_LOG_LEVEL: warn 
    networks: 
      plf:
    depends_on:
      - plf02