version: '3.0'

networks:
  search:

volumes:
  search_data:

services:
  search:
    image: exoplatform/elasticsearch:1.1.0
    environment:
      ES_JAVA_OPTS: "-Xms8g -Xmx8g"
      path.repo: "/backup"
      cluster.name: qaf05
      http.max_content_length: 400m
      xpack.monitoring.enabled: "false"
    ports:
      - "127.0.0.1:9200:9200"
    volumes:
      - /srv/bench/elasticsearch:/usr/share/elasticsearch/data
      - /srv/bench/backup/elasticsearch:/backup
    networks:
      search:
