---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: registry-pvc
  # namespace: kube-system
  labels:
    management: registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry-deployment
  labels:
    app: registry
  # namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        # kubernetes.io/cluster-service: "true"
    spec:
      volumes:
        - name: image-store
          persistentVolumeClaim:
            claimName: registry-pvc
      containers:
        - name: registry
          image: registry:2
          ports:
            - containerPort: 5000
          volumeMounts:
            - name: image-store
              mountPath: /var/lib/registry
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    service: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - name: registry
      port: 5000
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: registry-proxy
  # namespace: kube-system
  labels:
    k8s-app: registry
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: registry
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: registry.default.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000
