# From
# https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/registry
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-registry
  # namespace: kube-system
  # labels:
  #   kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
      storage: 10Gi
  hostPath:
    path: /data/pv-registry
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-registry
  # namespace: kube-system
  # labels:
  #   kubernetes.io/cluster-service: "true"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kube-registry
  # namespace: kube-system
  # labels:
  #   k8s-app: kube-registry
  #   version: v0
  #   kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  # selector:
  #   matchLabels:
  #     app: kube-registry
  template:
    metadata:
      labels:
        app: kube-registry
        version: v0
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: registry
        image: registry:2
        # resources:
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        env:
        - name: REGISTRY_HTTP_ADDR
          value: :5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        # volumeMounts:
        # - name: image-store
        #   mountPath: /var/lib/registry
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      # volumes:
      # - name: image-store
      #   persistentVolumeClaim:
      #     claimName: registry-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: kube-registry
  # namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "KubeRegistry"
spec:
  selector:
    k8s-app: kube-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-registry-proxy
  # namespace: kube-system
  labels:
    k8s-app: kube-registry
    kubernetes.io/cluster-service: "true"
    version: v0.4
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-registry
        kubernetes.io/name: "kube-registry-proxy"
        kubernetes.io/cluster-service: "true"
        version: v0.4
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.4
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: kube-registry.kube-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        ports:
        - name: registry
          containerPort: 80
          hostPort: 5000
