version: '3.0'

networks:
  plf:
{{- if ne .EXO_NODE_COUNT.V "1" }}
    driver: bridge
    # enable_ipv6: false
    ipam:
      driver: default
      config:
        - subnet: {{ .EXO_CLUSTER_IP_RANGE.V }}
{{- end }}
volumes:
  plf_node{{.NODE_ID.V}}:
  plf_shared:

services:
  plf1:
    image: exoplatform/exo:5.0_latest
    environment:
      EXO_ADDONS_LIST:
      EXO_ADDONS_REMOVE_LIST:
      EXO_DB_TYPE: mysql
      EXO_DB_NAME: plf
      EXO_DB_USER: plf
      EXO_DB_PASSWORD: plf
      EXO_DB_HOST: db
      EXO_DB_POOL_IDM_INIT_SIZE: {{.EXO_DB_POOL_IDM_INIT_SIZE.V}}
      EXO_DB_POOL_IDM_MAX_SIZE: {{.EXO_DB_POOL_IDM_MAX_SIZE.V}}
      EXO_DB_POOL_JCR_INIT_SIZE: {{.EXO_DB_POOL_JCR_INIT_SIZE.V}}
      EXO_DB_POOL_JCR_MAX_SIZE: {{.EXO_DB_POOL_JCR_INIT_SIZE.V}}
      EXO_DB_POOL_JPA_INIT_SIZE: {{.EXO_DB_POOL_JPA_INIT_SIZE.V}}
      EXO_DB_POOL_JPA_MAX_SIZE: {{.EXO_DB_POOL_JPA_INIT_SIZE.V}}
      EXO_PROXY_VHOST: {{.EXO_PUBLIC_HOSTNAME.V}}
      EXO_PROXY_SSL: "false"
      EXO_ES_EMBEDDED: "false"
      EXO_ES_HOST: search
      EXO_PROXY_PORT: 80
{{- if ne .EXO_NODE_COUNT.V "1" }}
      EXO_CLUSTER: "true"
      EXO_CLUSTER_HOSTS: "{{ .NODES_IPS.V }}"
      EXO_JGROUPS_ADDR: "{{ .EXO_CLUSTER_INSTANCE_IP_PREFIX.V }}.{{.NODE_ID.V}}"
      EXO_FILE_STORAGE_DIR: /srv/exo/shared/files
      EXO_JCR_STORAGE_DIR: /srv/exo/shared/jcrvalues
{{- end }}
      EXO_JVM_SIZE_MIN: "{{.EXO_JVM_SIZE.V}}"
      EXO_JVM_SIZE_MAX: "{{.EXO_JVM_SIZE.V}}"
      EXO_MAIL_SMTP_HOST: "mail"
      EXO_MAIL_SMTP_PORT: "1025"

      EXO_JMX_ENABLED: "true"
      EXO_JMX_RMI_REGISTRY_PORT: 10001
      EXO_JMX_RMI_SERVER_PORT: 10002
      EXO_JMX_RMI_SERVER_HOSTNAME: plf{{.NODE_ID.V}}

    volumes:
      - plf_node{{.NODE_ID.V}}:/srv/exo
      - plf_shared:/srv/exo/shared
    networks:
      - db
      - plf
      - search
      - mongo
      - front

  jmxtrans:
    image: exoplatform/jmxtrans:265_1
    container_name: jmxtrans
    environment:
      TARGET_JMX_HOST: plf{{.NODE_ID.V}}
      TARGET_HOSTNAME: plf{{.NODE_ID.V}}
      TARGET_JMX_PORT: 10001
      TARGET_INFLUXDB_URL: {{.INFLUXDB_HOST.V}}
      TARGET_INFLUXDB_DATABASE: exo
      TARGET_INFLUXDB_CREATE_DB: "true"
      JMXTRANS_LOG_LEVEL: info  #warn
      TARGET_NODE_ID: plf{{.NODE_ID.V}}
    networks:
      - plf

